# Generated by Django 5.0.1 on 2024-02-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='menu',
            new_name='MenuItem',
        ),
    ]
